/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfacesGraficas;

import static InterfacesGraficas.PrisonInterface.connect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Mañana
 */
public class VisitationInterface extends javax.swing.JPanel {

    /**
     * Creates new form VisitationInterface
     */
    public VisitationInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visitorTitle = new javax.swing.JLabel();
        visitorName = new javax.swing.JLabel();
        addVisitationDate = new javax.swing.JTextField();
        inmateId = new javax.swing.JLabel();
        addRelationship = new javax.swing.JTextField();
        visitationDate1 = new javax.swing.JLabel();
        addVisitorName = new javax.swing.JTextField();
        visitorName1 = new javax.swing.JLabel();
        addVisitorBornDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectInmates = new javax.swing.JTextArea();
        searchInmateButton = new javax.swing.JButton();
        visitorRelationship = new javax.swing.JLabel();
        addInmateId2 = new javax.swing.JTextField();
        submitVisitorButton = new javax.swing.JButton();

        visitorTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        visitorTitle.setText("Visitor creation formulary");

        visitorName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        visitorName.setText("Visitor born date");

        addVisitationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVisitationDateActionPerformed(evt);
            }
        });

        inmateId.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        inmateId.setText("Inmate ID");

        addRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRelationshipActionPerformed(evt);
            }
        });

        visitationDate1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        visitationDate1.setText("Visitation date");

        addVisitorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVisitorNameActionPerformed(evt);
            }
        });

        visitorName1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        visitorName1.setText("Visitor name");

        addVisitorBornDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVisitorBornDateActionPerformed(evt);
            }
        });

        selectInmates.setColumns(20);
        selectInmates.setRows(5);
        selectInmates.setName(""); // NOI18N
        jScrollPane1.setViewportView(selectInmates);

        searchInmateButton.setText("Search");
        searchInmateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInmateButtonActionPerformed(evt);
            }
        });

        visitorRelationship.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        visitorRelationship.setText("Relationship");

        addInmateId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInmateId2ActionPerformed(evt);
            }
        });

        submitVisitorButton.setText("Submit");
        submitVisitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVisitorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(visitorTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitVisitorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(109, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addVisitationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addVisitorName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addVisitorBornDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(179, 179, 179))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(visitorName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inmateId, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchInmateButton)
                                .addGap(52, 52, 52))
                            .addComponent(addInmateId2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(visitorName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visitorRelationship)
                        .addGap(25, 25, 25)))
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(visitationDate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(visitorTitle)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(visitationDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addVisitationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchInmateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(inmateId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addInmateId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visitorName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addVisitorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitorRelationship)
                    .addComponent(visitorName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVisitorBornDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(submitVisitorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addVisitationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVisitationDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVisitationDateActionPerformed

    private void addRelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRelationshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRelationshipActionPerformed

    private void addVisitorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVisitorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVisitorNameActionPerformed

    private void addVisitorBornDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVisitorBornDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVisitorBornDateActionPerformed

    private void searchInmateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInmateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInmateButtonActionPerformed

    private void addInmateId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInmateId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addInmateId2ActionPerformed
    public static Connection connect() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/prision";
        String user = "root";
        String password = "";

        return DriverManager.getConnection(url, user, password);
    }
    private void submitVisitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVisitorButtonActionPerformed
        /*SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        format.setLenient(false);
         */
        // Obtener los valores de las fechas
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        format.setLenient(false);
        String visitor_bornDate = dateFormat.format(addVisitorBornDate.getDate());
        String visitationDate = dateFormat.format(addVisitationDate.getDate());

        // Obtener los valores de la interfaz gráfica
        String visitorName = addVisitorName.getText();
        String relationship = addRelationship.getText();
        int inmate_ID = Integer.parseInt(addInmateId2.getText());

        // Sentencia SQL para insertar los datos en la base de datos
        String sql = "INSERT INTO visitation (visitation_date, inmate_ID, visitor_name, relationship) VALUES (?, ?, ?, ?)";

        try (Connection conn = connect(); PreparedStatement stmt = conn.prepareStatement(sql)) {
            // Establecer los parámetros de la consulta
            stmt.setString(1, visitationDate);
            stmt.setInt(2, inmate_ID);
            stmt.setString(3, visitorName);
            stmt.setString(4, relationship);

            // Ejecutar la consulta
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Prison inserted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to insert prison", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            // Manejo de errores de base de datos
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al insertar en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitVisitorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addInmateId2;
    private javax.swing.JTextField addRelationship;
    private javax.swing.JTextField addVisitationDate;
    private javax.swing.JTextField addVisitorBornDate;
    private javax.swing.JTextField addVisitorName;
    private javax.swing.JLabel inmateId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchInmateButton;
    private javax.swing.JTextArea selectInmates;
    private javax.swing.JButton submitVisitorButton;
    private javax.swing.JLabel visitationDate1;
    private javax.swing.JLabel visitorName;
    private javax.swing.JLabel visitorName1;
    private javax.swing.JLabel visitorRelationship;
    private javax.swing.JLabel visitorTitle;
    // End of variables declaration//GEN-END:variables
}
